export const managedTables = [
  "users",
  "warehouses",
  "clients",
  "products",
  "inventory",
  "locations",
  "orders",
  "order_items",
  "shipments",
  "receipts",
  "pickings",
  "tasks",
  "workers",
  "carriers",
  "zones",
  "lots",
  "cycle_counts",
  "adjustments",
  "returns",
  "kits",
  "vendors",
  "customers",
  "billing",
  "metrics",
  "audits",
  "exceptions",
  "configurations",
] as const;

export type ManagedTable = (typeof managedTables)[number];
