create index if not exists idx_users_warehouse_id on public.users (warehouse_id);
create index if not exists idx_users_client_id on public.users (client_id);
create index if not exists idx_customers_client_id on public.customers (client_id);
create index if not exists idx_products_client_id on public.products (client_id);
create index if not exists idx_zones_warehouse_id on public.zones (warehouse_id);
create index if not exists idx_locations_warehouse_id on public.locations (warehouse_id);
create index if not exists idx_locations_zone_id on public.locations (zone_id);
create index if not exists idx_lots_product_id on public.lots (product_id);
create index if not exists idx_inventory_client_id on public.inventory (client_id);
create index if not exists idx_inventory_warehouse_id on public.inventory (warehouse_id);
create index if not exists idx_inventory_lot_id on public.inventory (lot_id);
create index if not exists idx_receipts_vendor_id on public.receipts (vendor_id);
create index if not exists idx_receipts_warehouse_id on public.receipts (warehouse_id);
create index if not exists idx_receipts_client_id on public.receipts (client_id);
create index if not exists idx_orders_client_id on public.orders (client_id);
create index if not exists idx_orders_warehouse_id on public.orders (warehouse_id);
create index if not exists idx_order_items_order_id on public.order_items (order_id);
create index if not exists idx_order_items_product_id on public.order_items (product_id);
create index if not exists idx_shipments_carrier_id on public.shipments (carrier_id);
create index if not exists idx_workers_user_id on public.workers (user_id);
create index if not exists idx_workers_warehouse_id on public.workers (warehouse_id);
create index if not exists idx_pickings_worker_id on public.pickings (worker_id);
create index if not exists idx_tasks_warehouse_id on public.tasks (warehouse_id);
create index if not exists idx_cycle_counts_location_id on public.cycle_counts (location_id);
create index if not exists idx_adjustments_inventory_id on public.adjustments (inventory_id);
create index if not exists idx_adjustments_created_by on public.adjustments (created_by);
create index if not exists idx_returns_order_id on public.returns (order_id);
create index if not exists idx_metrics_warehouse_id on public.metrics (warehouse_id);
create index if not exists idx_audits_performed_by on public.audits (performed_by);

alter table public.warehouses enable row level security;
alter table public.clients enable row level security;
alter table public.users enable row level security;
alter table public.vendors enable row level security;
alter table public.customers enable row level security;
alter table public.carriers enable row level security;
alter table public.products enable row level security;
alter table public.zones enable row level security;
alter table public.locations enable row level security;
alter table public.lots enable row level security;
alter table public.inventory enable row level security;
alter table public.receipts enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.shipments enable row level security;
alter table public.workers enable row level security;
alter table public.pickings enable row level security;
alter table public.tasks enable row level security;
alter table public.cycle_counts enable row level security;
alter table public.adjustments enable row level security;
alter table public.returns enable row level security;
alter table public.kits enable row level security;
alter table public.billing enable row level security;
alter table public.metrics enable row level security;
alter table public.audits enable row level security;
alter table public.exceptions enable row level security;
alter table public.configurations enable row level security;
